{% set version = "1.9.5" %}

package:
  name: mdtraj
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mdtraj/mdtraj-{{ version }}.tar.gz
  sha256: f22c28c9dd51aa0f8692078dd3c2c7a338a7ca27cbd9aaeb669a60361e95adc4

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - mdconvert = mdtraj.scripts.mdconvert:entry_point
    - mdinspect = mdtraj.scripts.mdinspect:entry_point
  skip: True         # [python_impl == 'pypy']

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - zlib
    - msinttypes  # [win and py27]
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - scipy
    - pandas
    - pyparsing
    - pytables
    - astunparse
    - snappy
    - zlib

test:
  imports:
    - mdtraj
  commands:
    - mdconvert -h
    - mdinspect -h

about:
  home: https://github.com/mdtraj/mdtraj
  license: LGPL-2.1-or-later
  license_file: LICENSE
  summary: A modern, open library for the analysis of molecular dynamics trajectories
  description: |
    MDTraj is a python library that allows users to manipulate molecular dynamics
    (MD) trajectories and perform a variety of analyses, including fast RMSD,
    solvent accessible surface area, hydrogen bonding, etc. A highlight of MDTraj
    is the wide variety of molecular dynamics trajectory file formats which are
    supported, including RCSB pdb, GROMACS xtc, tng, and trr, CHARMM / NAMD dcd, AMBER
    binpos, AMBER NetCDF, AMBER mdcrd, TINKER arc and MDTraj HDF5.
  doc_url: http://mdtraj.org/
  dev_url: https://github.com/mdtraj/mdtraj

extra:
  recipe-maintainers:
    - rmcgibbo
    - mpharrigan
    - marscher
    - mattwthompson
