appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: hu+kRsB7T4kKJpo06ayUYYaCqU5C6OaltWAwLl7iTR697anoS/EOJbFp3PLeuq0bdvbdCVeZbxpTWImnnPseZfRrT3ZlGmzCkluuewAlFSME6pmQ0wMQsLvgwzaNbhqZWDhEsiHtPMpc9NPePxm4CdbTdiMUYx8gNMVOlEXvraWrh746lUJ2ZVkkb2u8CYSwBpcRMBxrYXF4z2371lQL1uZVGaxjrqgFz9+/zxziUT4cqQ5Lgi4kn3a3ioh8W9TKNQka0NwBfCp4r9CmjfHWzonqpe5d/gpU7N4WShcs6GsqtZBIweUnJ1nLaHYBaQpbKGscVKTd9wzy4aRfRkxoZMl6DfmM9NIwq1ZUjbG4TLHPM4c/td1CYdP8xJsZvClxXemIcuUj2WlMuf43iJjWrKuTz3vGxHiQeItimK7BEHTF7tdfX05WZSYRotUyr07VLNp1T71jVDMvl2gIP4f/QilgT4Jm1y5B+4JYF5hPg0P7TzHiUPhMzkqeY24hhPqwSIYYoxwSGMDk0pDe52w8/23qlnwJT0pt6MGbAk+Gljnd7/kJq2wGXGpyBz5DogYBLJDk49A7omls0j7ug48YLvio00agUiJ21MYXjl2NQeHRsmLt/n+1UT0o61AR2RHhqntXjof8N0noFU1/UvGS2Ac+iqm1wvqzXBmaF5Pq5hA=}
provider:
  win: azure
conda_forge_output_validation: true
